### ISSUE TITLE
Module versions with unicode

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-runtime#59]
``` bash
cd /tmp
ceylon new hello-world hello-world --ant=false --eclipse=false --module-name=tmp --module-version=version
cd hello-world/
ceylon compile tmp
ceylon run tmp/version
# Note: JBoss Modules version 1.1.3.GA 
# Hello, World!
sed -i 's/version/vερσiον/' source/tmp/module.ceylon
ceylon compile tmp
ceylon run tmp/vερσiον
# Note: JBoss Modules version 1.1.3.GA 
# ceylon run: Invalid module name or version: contains invalid characters
```

That message is printed [here](https://github.com/ceylon/ceylon-runtime/blob/7a456a784688e5d91a26ea93344481d4fe195231/impl/src/main/java/ceylon/modules/jboss/runtime/AbstractJBossRuntime.java#L71).

If you try to create that version directly with `ceylon new`, you get this instead:

> ceylon new hello-world hello-world-2 --ant=false --eclipse=false --module-name=tmp --module-version=vερσiον
> ceylon new: Invalid value: vερσiον
> java.lang.RuntimeException: Invalid value: vερσiον
>     at com.redhat.ceylon.tools.new_.Variable.initialize([Variable.java:70](https://github.com/ceylon/ceylon-compiler/blob/bfb2f1e276d89f52ca081b3d0022d0827f262b61/src/com/redhat/ceylon/tools/new_/Variable.java#L70))
>     at com.redhat.ceylon.tools.new_.CeylonNewTool.buildPromptedEnv([CeylonNewTool.java:151](https://github.com/ceylon/ceylon-compiler/blob/bfb2f1e276d89f52ca081b3d0022d0827f262b61/src/com/redhat/ceylon/tools/new_/CeylonNewTool.java#L151))
>     at com.redhat.ceylon.tools.new_.CeylonNewTool.run([CeylonNewTool.java:104](https://github.com/ceylon/ceylon-compiler/blob/bfb2f1e276d89f52ca081b3d0022d0827f262b61/src/com/redhat/ceylon/tools/new_/CeylonNewTool.java#L104))
>     at com.redhat.ceylon.common.tools.CeylonTool.run([CeylonTool.java:343](https://github.com/ceylon/ceylon-common/blob/ce186be04aaa1b13c61747a97acb15eacc6f55d8/src/com/redhat/ceylon/common/tools/CeylonTool.java#L343))
>     at com.redhat.ceylon.common.tools.CeylonTool.execute([CeylonTool.java:283](https://github.com/ceylon/ceylon-common/blob/ce186be04aaa1b13c61747a97acb15eacc6f55d8/src/com/redhat/ceylon/common/tools/CeylonTool.java#L283))
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:82)
>     at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:21)
> <sup>Generated by [linkStacktrace](http://lucaswerkmeister.github.io/linkStacktrace/)</sup>

Found around [here](https://groups.google.com/d/msg/ceylon-users/UZDhaNcfxtc/i8yH1_78ch8J). @tombentley here’s your issue, I used the repository that contains the error message.

**Comment by tombentley** [comment]
This has just been fixed in jboss module's upstream: https://issues.jboss.org/browse/MODULES-190

**Comment by FroMage** [comment]
Err, didn't we move that issue?
