### ISSUE TITLE
java.lang.NoClassDefFoundError with org.codehause.jettison

### ISSUE THREAD

**Issue by Tokiru** [ceylon/ceylon-runtime#84]
my module.ceylon looks like this:

```
shared import "com.thoughtworks.xstream:xstream" "1.4.8";
shared import "org.codehaus.jettison:jettison" "1.2";
```

The code

```
value x = JettisonMappedXmlDriver();
```

causes 

``````
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/jettison/mapped/Configuration
    at com.thoughtworks.xstream.io.json.JettisonMappedXmlDriver.<init>(JettisonMappedXmlDriver.java:55)
    at main.run_.run(run.ceylon:12)
    at main.run_.main(run.ceylon)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
    at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
    at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:65)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:102)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:98)
    at ceylon.modules.Main.execute(Main.java:69)
    at ceylon.modules.Main.main(Main.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.modules.Module.run(Module.java:308)
    at org.jboss.modules.Main.main(Main.java:487)
    at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:269)
    at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:491)
    at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:115)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
    at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
Caused by: java.lang.ClassNotFoundException: org.codehaus.jettison.mapped.Configuration from [Module "com.thoughtworks.xstream\:xstream:1.4.8" from Ceylon ModuleLoader: RootRepositoryManager: FileContentStore: /home/nostroumov/.ceylon/cache]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
    ... 31 more
``` at runtime.
``````

**Comment by thradec** [comment]
this repository is deprecated use ceylon/ceylon please

**Comment by Tokiru** [comment]
instead of what?

**Comment by thradec** [comment]
this issue belongs here https://github.com/ceylon/ceylon/issues/new

**Comment by Tokiru** [comment]
oh, sorry

**Comment by thradec** [comment]
np :-)
